version: '3.7'

services:
  nginx:
    build: ./dockerfiles/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - wordpress

  wordpress:
    build: ./dockerfiles/wordpress
    environment:
      WORDPRESS_DB_HOST: postgres
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./data/wp:/var/www/html
    depends_on:
      - postgres

  certbot:
    build: ./dockerfiles/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  postgres:
    build: ./dockerfiles/postgres
    environment:
      POSTGRES_USER: wordpress
      POSTGRES_PASSWORD: wordpress
      POSTGRES_DB: wordpress_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
